import { ServiceData } from "@/types/service";

export const services: ServiceData[] = [
  {
    id: "lead-engine",
    name: "AI Lead Engine & Growth Web Presence",
    tagline: "High-converting web architecture with integrated AI sales assistant",
    regularPrice: "$1,200–$1,800 setup + $300–$400/mo",
    foundingPrice: "$700–$800 setup + $250/mo",
    spotsLeft: 3,
    deliveryTime: "5–7 business days",
    paymentTerms: "50% upfront / 50% upon delivery",
    includes: [
      "Up to 5 custom layout sections",
      "Custom-trained AI Lead Chatbot",
      "Appointment scheduling (Calendly/Cal.com)",
      "Email & SMS instant lead alerts",
      "Validated contact & lead capture forms",
      "GA4 & Meta Pixel analytics setup",
      "Vercel deployment & custom domain config",
    ],
    excludes: [
      "Copywriting from scratch",
      "Branding / Logo design",
      "Advanced SEO campaigns",
      "More than 5 sections",
    ],
    ctaLabel: "Select AI Lead Engine",
  },
  {
    id: "process-automation",
    name: "Business Process Automation & Dashboard",
    tagline: "Custom operations portal to eliminate manual work and spreadsheet chaos",
    regularPrice: "$3,500–$4,800",
    foundingPrice: "$2,200–$2,500",
    spotsLeft: 2,
    deliveryTime: "2–3 weeks",
    paymentTerms: "50/50 or 40/30/30 milestone options",
    includes: [
      "Operational workflow audit",
      "Custom Next.js + Supabase dashboard",
      "Admin & Staff role-based access control (RBAC)",
      "Automated PDF generation (Quotes & Invoices)",
      "Up to 3 third-party API integrations",
      "Data migration from Excel / CSV",
      "1 week of dedicated post-launch support",
    ],
    excludes: [
      "More than 3 integrations",
      "Maintenance outside support window",
    ],
    ctaLabel: "Select Automation Package",
  },
  {
    id: "custom-mvp",
    name: "Full-Stack Custom Web App / SaaS MVP",
    tagline: "Production-ready MVP built to scale and attract early users or investors",
    regularPrice: "$6,000–$7,500",
    foundingPrice: "$3,200–$3,500",
    spotsLeft: 2,
    deliveryTime: "3–5 weeks",
    paymentTerms: "40/30/30 milestone payments",
    includes: [
      "Authentication & RBAC permissions",
      "Client portal & Admin management panel",
      "Up to 5 core functional modules (Stripe, Reports, Files, AI)",
      "Production deployment on Vercel",
      "2 weeks of dedicated post-launch support",
    ],
    excludes: [
      "Native mobile app",
      "Branding & design kit",
      "More than 5 core modules",
    ],
    ctaLabel: "Select SaaS MVP Package",
  },
];
